In [1]:
import tensorflow as tf;

In [3]:
!pip install random

ERROR: Could not find a version that satisfies the requirement random (from versions: none)
ERROR: No matching distribution found for random

In [2]:
import numpy as np
import random as rn
import pandas as pd
import os
import glob
import datetime
import yfinance as yf

In [5]:
msft = yf.Ticker("MSFT")
msft.actions

                           Dividends  Stock Splits
Date
1987-09-21 00:00:00-04:00       0.00           2.0
1990-04-16 00:00:00-04:00       0.00           2.0
1991-06-27 00:00:00-04:00       0.00           1.5
1992-06-15 00:00:00-04:00       0.00           1.5
1994-05-23 00:00:00-04:00       0.00           2.0
...                              ...           ...
2022-08-17 00:00:00-04:00       0.62           0.0
2022-11-16 00:00:00-05:00       0.68           0.0
2023-02-15 00:00:00-05:00       0.68           0.0
2023-05-17 00:00:00-04:00       0.68           0.0
2023-08-16 00:00:00-04:00       0.68           0.0

[88 rows x 2 columns]

In [6]:
data = yf.download("AAPL", period="1mo")

[*********************100%%**********************]  1 of 1 completed

In [8]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-09-13,176.509995,177.300003,173.979996,174.210007,174.210007,84267900
2023-09-14,174.000000,176.100006,173.580002,175.740005,175.740005,60895800
2023-09-15,176.479996,176.500000,173.820007,175.009995,175.009995,109205100
2023-09-18,176.479996,179.380005,176.169998,177.970001,177.970001,67257600
2023-09-19,177.520004,179.630005,177.130005,179.070007,179.070007,51826900
2023-09-20,179.259995,179.699997,175.399994,175.490005,175.490005,58436200
2023-09-21,174.550003,176.300003,173.860001,173.929993,173.929993,63047900
2023-09-22,174.669998,177.080002,174.050003,174.789993,174.789993,56725400
2023-09-25,174.199997,176.970001,174.149994,176.080002,176.080002,46172700
2023-09-26,174.820007,175.199997,171.660004,171.960007,171.960007,64588900
2023-09-27,172.619995,173.039993,169.050003,170.429993,170.429993,66921800
2023-09-28,169.339996,172.029999,167.619995,170.690002,170.690002,56294400
2023-09-29,172.020004,173.070007,170.339996,171.210007,171.210007,51814200
2023-10-02,171.220001,174.300003,170.929993,173.750000,173.750000,52164500
2023-10-03,172.259995,173.630005,170.820007,172.399994,172.399994,49594600
2023-10-04,171.089996,174.210007,170.970001,173.660004,173.660004,53020300
2023-10-05,173.789993,175.449997,172.679993,174.910004,174.910004,48527900
2023-10-06,173.800003,177.990005,173.179993,177.490005,177.490005,57224100
2023-10-09,176.809998,179.050003,175.800003,178.990005,178.990005,42390800
2023-10-10,178.100006,179.720001,177.949997,178.389999,178.389999,43698000
2023-10-11,178.199997,179.850006,177.600006,179.800003,179.800003,47551100
2023-10-12,180.070007,182.339996,179.039993,180.710007,180.710007,56608967